<a href="https://colab.research.google.com/github/mrgoudsaab/Ranjithgoud/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10],[2,12,23,10,89]])
print(arr)
print('0th element on 2nd row: ', arr[2,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2 12 23 10 89]]
0th element on 2nd row:  89


In [ ]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr)
print(arr[1,1,])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
5


In [ ]:
import pandas as pd

sales_data = {
   'TransactionID' : [1, 2, 3, 4, 5],
   'CustomerID' : [101, 102, 103, 104, 101],
   'Amount' : [250, 300, 400, 500, 600],
   'Date' : ['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05']
}
customer_data = {
     'CustomerID' : [101, 102, 103, 104],
     'CustomerName' : ['Alice', 'Bob', 'Charlie', 'David'],
     'Age' : [30, 35, 40, 25],
     'City' : ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
sales_df = pd.DataFrame(sales_data)
customer_data = pd.DataFrame(customer_data)
print(sales_df)
print(customer_data)
print("Shape of sales data:", sales_df.shape)
print("Sales data statistics:")
print(sales_df.describe())
print("Sales dataframe",sales_df)
print("customer_df",customer_data)


   TransactionID  CustomerID  Amount        Date
0              1         101     250  2025-01-01
1              2         102     300  2025-01-02
2              3         103     400  2025-01-03
3              4         104     500  2025-01-04
4              5         101     600  2025-01-05
   CustomerID CustomerName  Age         City
0         101        Alice   30     New York
1         102          Bob   35  Los Angeles
2         103      Charlie   40      Chicago
3         104        David   25      Houston
Shape of sales data: (5, 4)
Sales data statistics:
       TransactionID  CustomerID      Amount
count       5.000000     5.00000    5.000000
mean        3.000000   102.20000  410.000000
std         1.581139     1.30384  143.178211
min         1.000000   101.00000  250.000000
25%         2.000000   101.00000  300.000000
50%         3.000000   102.00000  400.000000
75%         4.000000   103.00000  500.000000
max         5.000000   104.00000  600.000000
Sales dataframe    Transa